# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vecerka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2018, 12, 29, 14, 31, 18, 941680, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
