export const MARKER_LIST_REQUEST = 'MARKER_LIST_REQUEST'
export const MARKER_LIST_SUCCESS = 'MARKER_LIST_SUCCESS'
export const MARKER_LIST_FAILURE = 'MARKER_LIST_FAILURE'

export const ADD_MARKER_REQUEST = 'ADD_MARKER_REQUEST'
export const ADD_MARKER_SUCCESS = 'ADD_MARKER_SUCCESS'
export const ADD_MARKER_FAILURE = 'ADD_MARKER_FAILURE'
